#!/bin/bash

# This script is a wrapper for the vpt command in the conda environment

# Activate the conda environment
eval "$(conda shell.bash hook)"
conda activate vpt-env

# Call the actual vpt command with all arguments
/beegfs/scratch/ric.broccoli/kubacki.michal/conda/envs/vpt-env/bin/vpt "$@"